In [2]:
import numpy as np

In [3]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.save("one_array",x)

In [6]:
!ls

anaconda3			   Desktop
Anaconda3-2019.03-Linux-x86_64.sh  one_array.npy
Array的Input和Output.ipynb	   数组与矩阵运算.ipynb


In [8]:
np.load("one_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
y = np.arange(20)

In [10]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.savez("two_array.npz", a=x,b=y)

In [15]:
c = np.load("two_array.npz")

In [17]:
!ls

anaconda3			   Desktop	  数组与矩阵运算.ipynb
Anaconda3-2019.03-Linux-x86_64.sh  one_array.npy
Array的Input和Output.ipynb	   two_array.npz


In [18]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])