# 

In [1]:
import numpy as np

In [2]:
list_1 = [1,2,3,4]

In [3]:
list_1

[1, 2, 3, 4]

In [4]:
array_1 = np.array(list_1)

In [5]:
array_1

array([1, 2, 3, 4])

In [6]:
list_2 = [5,6,7,8]

In [7]:
arrary_2 = np.array(list_2)

In [8]:
arrary_2

array([5, 6, 7, 8])

In [9]:
arrary_list = np.array([list_1, list_2])

In [10]:
arrary_list

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arrary_list.shape

(2, 4)

In [12]:
arrary_list.size

8

In [13]:
arrary_list.dtype

dtype('int64')

In [14]:
arrary_3 = np.arrary([[1.0,2,3],[4.0,5,6]])

AttributeError: module 'numpy' has no attribute 'arrary'

In [15]:
arrary_3 = np.array([[1.0,2,3],[4.0,5,6]])

In [16]:
arrary_3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
arrary_3.dtype

dtype('float64')

In [20]:
arrary_4 = np.arange(1,10,2)

In [21]:
arrary_4

array([1, 3, 5, 7, 9])