# 生成随机数

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([0.78621511, 1.72749844, 0.30438317, 1.2401656 , 0.06564136,
       0.95457393, 1.41082038, 0.24568692, 0.10339761, 1.1448363 ])

In [7]:
np.random.randint(10)

7

In [8]:
np.random.randint(10,size=(2,3))

array([[7, 2, 9],
       [2, 3, 7]])

In [9]:
np.random.randint(10,size=20)

array([4, 0, 3, 6, 2, 4, 6, 4, 4, 4, 8, 3, 3, 2, 5, 5, 8, 8, 8, 9])

In [10]:
np.random.randint(10,size=20).reshape(4,5)

array([[5, 6, 0, 8, 2],
       [0, 8, 2, 6, 3],
       [9, 7, 5, 1, 2],
       [9, 4, 4, 4, 7]])

# 数组运算

In [11]:
a = np.random.randint(10,size=20).reshape(4,5)
b = np.random.randint(10,size=20).reshape(4,5)

In [13]:
a + b

array([[ 4, 11, 13, 11,  6],
       [ 9, 10,  6, 13, 12],
       [12, 13, 13, 14, 10],
       [15,  6, 13, 17,  9]])

In [14]:
a - b

array([[ 2,  1,  3,  5, -4],
       [-7, -8, -6,  3, -6],
       [ 2, -3, -3,  2,  0],
       [ 3,  4,  3,  1,  9]])

In [15]:
a * b

array([[ 3, 30, 40, 24,  5],
       [ 8,  9,  0, 40, 27],
       [35, 40, 40, 48, 25],
       [54,  5, 40, 72,  0]])

In [16]:
a / b

/home/learndata/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[3.        , 1.2       , 1.6       , 2.66666667, 0.2       ],
       [0.125     , 0.11111111, 0.        , 1.6       , 0.33333333],
       [1.4       , 0.625     , 0.625     , 1.33333333, 1.        ],
       [1.5       , 5.        , 1.6       , 1.125     ,        inf]])

## 数组除法要求不能有0为除数

# 矩阵

In [18]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [19]:
a

array([[3, 6, 8, 8, 1],
       [1, 1, 0, 8, 3],
       [7, 5, 5, 8, 5],
       [9, 5, 8, 9, 9]])

In [20]:
np.mat(a)

matrix([[3, 6, 8, 8, 1],
        [1, 1, 0, 8, 3],
        [7, 5, 5, 8, 5],
        [9, 5, 8, 9, 9]])

# 矩阵运算

In [22]:
A = np.mat(a)

In [23]:
B = np.mat(b)

In [24]:
A

matrix([[3, 6, 8, 8, 1],
        [1, 1, 0, 8, 3],
        [7, 5, 5, 8, 5],
        [9, 5, 8, 9, 9]])

In [28]:
B

matrix([[1, 5, 5, 3, 5],
        [8, 9, 6, 5, 9],
        [5, 8, 8, 6, 5],
        [6, 1, 5, 8, 0]])

In [26]:
A + B

matrix([[ 4, 11, 13, 11,  6],
        [ 9, 10,  6, 13, 12],
        [12, 13, 13, 14, 10],
        [15,  6, 13, 17,  9]])

In [27]:
A - B

matrix([[ 2,  1,  3,  5, -4],
        [-7, -8, -6,  3, -6],
        [ 2, -3, -3,  2,  0],
        [ 3,  4,  3,  1,  9]])

## 两个矩阵乘法运算A矩阵的行数和B矩阵的列数要相同，下面修改下

In [29]:
a = np.mat(np.random.randint(10,size=20).reshape(4,5))
b = np.mat(np.random.randint(10,size=20).reshape(5,4))

In [30]:
a * b

matrix([[113, 122, 135, 129, 100],
        [101, 117, 125, 114,  91],
        [108, 173, 149, 109, 152],
        [ 80, 105,  95,  79,  94],
        [147, 141, 153, 154, 117]])

# Array 常用函数，矩阵用的比较少，数组用的比较多

In [31]:
a = np.random.randint(10,size=20).reshape(4,5)

In [32]:
np.unique(a)

array([0, 2, 3, 4, 5, 7, 8])

In [33]:
a

array([[8, 3, 4, 8, 5],
       [5, 2, 0, 8, 3],
       [2, 4, 4, 5, 0],
       [7, 5, 4, 4, 4]])

In [34]:
sum(a)

array([22, 14, 12, 25, 12])

In [35]:
sum(a[0])

28

In [38]:
sum(a[:,0])

22

In [39]:
max(a[0])

8

In [40]:
max(a[:,0])

8

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])